name: "RPi5 OLED Monitor"
version: "1.0.5"
slug: rpi5_oled
description: "Display system info on I2C OLED"
url: "https://github.com/davidelolli/homeassistant-rpi5-oled"
arch:
  - aarch64
devices:
  - /dev/i2c-0:rw
privileged: true
startup: application
boot: auto
options: {}
schema: {}
